### ISSUE TITLE
How to create a client without the "with" statement ?

### ISSUE THREAD

**Issue by lucj** [Gr1N/nats-python#12]
Hi, thanks a lot for nats-python, that is a great project.
I have a very small class with static methods: the first one to initialize the connection and save it in a class variable, the second one to publish a message. It basically looks like the following.

```
class NATS(object):
    NATS_URL = os.getenv('NATS_URL', 'nats://nats:4222')
    client = None

    @staticmethod
    def initialize():
        while True:
            time.sleep(1)
            try:
                with NATSClient(NATS.NATS_URL) as client:
                    NATS.client = client
                    logging.debug("-> connected to NATS")
                return
            except Exception as e:
                logging.debug("-> cannot connect to NATS, retrying...")
                pass

    @staticmethod
    def publish(event):
        try:
           NATS.client.publish(">", payload=json.dumps(event).encode())
        except Exception as e:
             logging.error(str(e))
```

It is called from another module with:
```
NATS.initialize()
NATS.publish({"test":"1"})
```

But, as the connection is done with ```NATSClient(NATS.NATS_URL) as client```, the file descriptor is closed right after the ```with``` instruction. I then get the following error when trying to publish a message.

```
ERROR:root:[Errno 9] Bad file descriptor
```

Is there a way to create a client without using "with" so the socket handler is not closed ?
Thanks a lot

**Comment by Gr1N** [comment]
Hi!

You can just import client and initialize it without context manager, something like this:
```python
client = NATSClient("nats://127.0.0.1:4222")
client.connect()
```

More examples you can find at https://github.com/Gr1N/nats-python/blob/1fcf571b2deb6d444cbd44c63f9ff42844243e88/tests/test_client.py#L18-L23

**Comment by lucj** [comment]
Wow, thanks, that was really quick.
This is working great.
