### ISSUE TITLE
How to set tls options?

### ISSUE THREAD

**Issue by vadim-shadrin** [Gr1N/nats-python#16]

**Comment by Gr1N** [comment]
Hi!

You can pass them during client initialization: https://github.com/Gr1N/nats-python/blob/master/pynats/client.py#L122-L126

```python
nats = NATSClient(tls_cacert=..., tls_client_cert=..., tls_client_key=..., tls_hostname=..., tls_verify=...)
```

**Comment by vadim-shadrin** [comment]
Спасибо, не догадался. Сбила с толку официальная дока .

  
>Четверг, 2 июля 2020, 13:06 +03:00 от Nikita Grishko <notifications@github.com>:
> 
> 
>Hi!
>You can pass them during client initialization:  https://github.com/Gr1N/nats-python/blob/master/pynats/client.py#L122-L126
>nats = NATSClient(tls_cacert=..., tls_client_cert=..., tls_client_key=..., tls_hostname=..., tls_verify=...)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Vadim Shadrin
+7 960-763-5652
