### ISSUE TITLE
How to perform request-response inside one NATSClient object?

### ISSUE THREAD

**Issue by danylott** [Gr1N/nats-python#21]
I really appreciate your project, and glad to see it developing, 
But I'm wondering, is it possible to do request-response inside `one` NATSClient?
I've copied your example from README.md & modified it a bit:
```python
from pynats import NATSClient

with NATSClient() as client:
    # Connect
    client.connect()

    # Subscribe
    def callback(msg):
        print(f"Received a message with subject {msg.subject}: {msg}")
        client.publish(subject=msg.reply, payload=b"test-response")

    client.subscribe(subject="test-subject", callback=callback)

    # Request a message
    print(client.request(subject="test-subject", payload=b"test-payload"))
```
Btw, I was waiting to see the response, but I've got an error instead:
```
Traceback (most recent call last):
    client.request(subject="test-subject", payload=b"test-payload")
  File ".../python3.8/site-packages/pynats/client.py", line 291, in request
    return reply_messages[sub.sid]
KeyError: 1
Received a message with subject test-subject: NATSMessage(sid=0, subject='test-subject', reply='_INBOX.jR2XP1kZIIGMIz3ldUYbYX ', payload=b'test-payload')
```

I'm using Ubuntu 20.04 with python 3.8.5 & nats-python==0.8.0.
Will really appreciate your support

**Comment by Gr1N** [comment]
Hi and sorry for the late answer. 

Yes, it's possible. Can you please share more details like the version of NATS you use and more details traceback if it's possible

**Comment by danylott** [comment]
Hello, I'm using nats-server version 0.9.4.
I'll be happy to provide more details & traceback, but here is everything I have, from the script:
```
(venv) danylott@danylott:~/work$ python pntest.py 
Received a message with subject test-subject: NATSMessage(sid=0, subject='test-subject', reply='_INBOX.heatC52hnPExgp1AZYcBi6 ', payload=b'test-payload')
Traceback (most recent call last):
  File "pntest.py", line 15, in <module>
    print(client.request(subject="test-subject", payload=b"test-payload"))
  File "python3.8/site-packages/pynats/client.py", line 291, in request
    return reply_messages[sub.sid]
KeyError: 1
```
If I change `client.request` to `client.publish` in the script at the top - everything works fine (but it is not the request).
If you said, that it is possible, to do request-response using only 1 NatsClient - could you provide an example please?

**Comment by Gr1N** [comment]
I guess I understand what is your problem is. And yes unfortunately due to the very simple design of the library is not possible to subscribe to the callback and send requests at once. But if you split your code into two processes (server and client) you will achieve what you want.

Something like:
```python
# server.py
from pynats import NATSClient

with NATSClient() as client:
    # Connect
    client.connect()

    # Subscribe
    def callback(msg):
        print(f"Received a message with subject {msg.subject}: {msg}")
        client.publish(subject=msg.reply, payload=b"test-response")

    client.subscribe(subject="test-subject", callback=callback)
    client.wait()
```
```python
# client.py
from pynats import NATSClient

with NATSClient() as client:
    # Connect
    client.connect()

    # Request 
    print(client.request(subject="test-subject", payload=b"test-payload"))
```

**Comment by danylott** [comment]
Okay, thank you, I got this :smile:
