### ISSUE TITLE
Subscribe does not pass queue to nats-server

### ISSUE THREAD

**Issue by lijianbing** [Gr1N/nats-python#3]
git diff
diff --git a/pynats/client.py b/pynats/client.py
index 9b23311..8083063 100644
--- a/pynats/client.py
+++ b/pynats/client.py
@@ -166,7 +166,7 @@ class NATSClient:
         sub = NATSSubscription(
             sid=self._ssid,
             subject=subject,
-            queue="",
+            queue=queue,
             callback=callback,
             max_messages=max_messages,
         )

**Comment by Gr1N** [comment]
Hi! Thank you for the bug report! I will fix it ASAP. Anyway, PR is always welcome!

**Comment by Gr1N** [comment]
New version with fix released https://github.com/Gr1N/nats-python/releases/tag/0.5.0.
Enjoy!
