### ISSUE TITLE
Does this client work out of the box with a postgres backend?

### ISSUE THREAD

**Issue by samklonaris** [Gr1N/nats-python#8]
I'm running the streaming server locally with 
```
nats-streaming-server --debug -store sql -sql_driver postgres --sql_source="user=postgres password=postgres host=localhost port=5432 sslmode=disable database=nats"
```

In one process I write messages with:
```
with NATSClient(url='nats://0.0.0.0:4222', socket_timeout=2) as client:
    client.publish(
        'message-name',
        payload=json.dumps({'sample_payload_id': 1})
     )
```

In another process I am trying to read them with:
```
with NATSClient(url='nats://0.0.0.0:4222', socket_timeout=2) as client:
   client.subscribe(
        'message-name',
        callback=message_callback
    )
   client.wait(count=1)
```

In this second process I keep getting socket timeouts.  I've also checked my database, and don't see any messages in the table.

**Comment by Gr1N** [comment]
As I see you use NATS Streaming Server and this package does not support it. And honestly, I have no plans for adding support.

If you need a Python client for NATS Streaming Server then try to use https://nats.io/download/nats-io/stan.py/.

**Comment by samklonaris** [comment]
Thanks for the reply!
